### Post users
POST http://localhost:3000/users
Content-Type: application/json

### Get users
GET http://localhost:3000/users
Content-Type: application/json

### Get user
GET http://localhost:3000/users/redirect/docs
Content-Type: application/json

### Patch user
PATCH http://localhost:3000/users/1
Content-Type: application/json

### Post user
DELETE http://localhost:3000/users/1
Content-Type: application/json