### dto 테스트 - create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test-name",
  "email": "test@email.com",
  "password": "test-password"
}

### dto 테스트 - email 인증
POST http://localhost:3000/users/email-verify?signupVerifyToken=test_token
Content-Type: application/json


### dto 테스트 - 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "test-password"
}

### dto 테스트 - 회원 정보 조회
GET http://localhost:3000/users/user-id
Content-Type: application/json